### ISSUE TITLE
Code kann nicht mehr ausgeführt werden.

### ISSUE THREAD

**Issue by elisabeth-werner** [BMCV/mobi-fs3-python#13]
### Repository

[mobi-fs3-python](https://github.com/elisabeth-werner/mobi-fs3-python)

### Access rights

- [X] I hereby confirm that the supervisors can access my GitHub repository.

### Git commit and push

- [X] I hereby confirm that I have committed and pushed to my GitHub repository.

### Task

Übungsblatt 3

### Describe the problem (if possible)

Guten Tag,
ich wollte zur Klausurvorbereitung die Übungsblätter 3 & 4 gerne in Ruhe durcharbeiten. Jedes Mal wenn ich nun einen Code ausführen möchte, unabhängig vom Übungsblatt oder der Aufgabe, funktioniert dies nicht. Ich werde jedes Mal nach einem Kernel gefragt. Ich kann auch nicht wie in Aufgabe 1.3 beschrieben "Python Environment" und "Python 3.11.6" auswählen, da es nur ein Eingabefeld für Kernel gibt. Wenn ich dort die Auswahl eintippe, schließt sich zwar das Fenster, der Code wird jedoch immer noch nicht ausgeführt und bei erneutem versuchen, erscheint wieder das Feld zur Kernel-Auswahl.
Gibt es irgendeine Möglichkeit das wieder zum Laufen zu bringen.
Vielen Dank.

**Comment by kostrykin** [comment]
Thanks for reaching out! @elisabeth-werner 

The issue which you describe has already been reported by multiple of your classmates. Therefore, in last session on Thursday, Feb 8, we had taken some time to address the issue and describe the solution to everyone present in the class room. Please do the following:

1. Make sure that all your code changes are committed and pushed (otherwise they will be lost when you proceed).
2. Delete your Codespace by going to https://github.com/codespaces, clicking on the three dots next to your Codespace, and then clicking on _Delete_ (also see the screenshot below).
3. Then, go back to [your repo](https://github.com/elisabeth-werner/mobi-fs3-python), and re-create the codespace as described in Task 2 of Lab Session 1.

So far, everyone has reported that this had solved the issue. Please report back too! :)

<img width="336" alt="delete-codespace" src="https://github.com/BMCV/mobi-fs3-python/assets/6557139/581fd65f-2311-43d4-b740-0e89f7f12d9f">

**Comment by elisabeth-werner** [comment]
Thank you very much, that has solved my problem and now everything works perfectly again.
